### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by lindy65**
Hi @goern,

Mattermost v4.4.1 release is officially out.  

You can [find download links with hash numbers here](https://pre-release.mattermost.com/core/pl/ph9peatubtne7pszys4utsyo3c).  Changelog with notes on patch releases is available [here](https://docs.mattermost.com/administration/changelog.html#release-v4-4-1).

If you do update, please consider tweeting about it, which we can then re-tweet for greater reach.

Thanks!

### CODE REVIEW

**Comment by goern** [comment]
heya, have a look at #37 and let me know what you think.

Cc: @sapkra

**Comment by lindy65** [comment]
It's automated :) Thats awesome!

Is there anything I should be doing differently when we ship a new release or is submitting a PR as I have been doing sufficient/correct?

**Comment by goern** [comment]
The script I did will read through the mattermost-server released and check if you got some newer version than the dockerfile in this repo. It would be great if you could have a look at if for 2...3... released and just double check that the script is doing good. 
No need for you to send any PR, I just need to put the script on heroku or so...

**Comment by sapkra** [comment]
Files they should also be updated:
- mattermost.yaml
- README.md

Both files still have the old version.

**Comment by goern** [comment]
@sapkra right, I am happy to see a pull request for that. It is actually a good starter PR. Let me know if you need some help but if feels straight forward.

**Pull request closed without merging**
